code/.idea/gradle.xml
code/app/.gitignore
code/app/build.gradle
code/build.gradle

I set up the Firebase according to #44. I added the google services json to the gitignore for security and made changes to the gradle files accordingly. I also added everyone to the firebase project.
@CMPUT301W21T03/main Can each of you confirm that you can access [the firebase project](https://console.firebase.google.com/) in your browser? (Log in with your ualberta account)

firebase setup

---

code/app/src/main/java/com/example/experiment_automata/User.java

quick refactor to match userId change in Experiment class

changed userId from int to UUID

---

code/app/build.gradle
code/app/src/main/java/com/example/experiment_automata/AddExperimentFragment.java
code/app/src/main/java/com/example/experiment_automata/BinomialExperiment.java
code/app/src/main/java/com/example/experiment_automata/CountExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiment.java
code/app/src/main/java/com/example/experiment_automata/ExperimentMaker.java
code/app/src/main/java/com/example/experiment_automata/IllegalExperimentException.java
code/app/src/main/java/com/example/experiment_automata/MainActivity.java
code/app/src/main/java/com/example/experiment_automata/MeasurementExperiment.java
code/app/src/main/java/com/example/experiment_automata/NaturalCountExperiment.java
code/app/src/main/res/layout/activity_main.xml
code/app/src/main/res/layout/fragment_add_experiment.xml
code/app/src/main/res/values/colors.xml
code/app/src/main/res/values/strings.xml

Dialog created that is identical to the design in the storyboard (except for the locale field since I wasn't sure the purpose of it).
Added the ability to create experiments with more information in the ExperimentMaker based on inputs used in the Dialog.
Added a small button to MainActivity and implemented code to easily test the Dialog on this screen via the debug console.
Javadocs comments were written and citations were added where appropriate in code.
I have no unit testing since from what I can tell there's no simple way to do it on a dialog.
Added attributes to experiment class to tell you if an experiment is accepting new results and if it records information.
Utilized the strings and color resource section in the creation of the dialog

Make experiment

---

code/app/build.gradle
code/app/src/main/AndroidManifest.xml
code/app/src/main/java/com/example/experiment_automata/AddExperimentFragment.java
code/app/src/main/java/com/example/experiment_automata/Experiment.java
code/app/src/main/java/com/example/experiment_automata/ExperimentMaker.java
code/app/src/main/java/com/example/experiment_automata/Subscription.java
code/app/src/main/java/com/example/experiment_automata/User.java
code/app/src/test/java/com/example/experiment_automata/ExampleUnitTest.java
code/app/src/test/java/com/example/experiment_automata/ExperimentMakerTests.java
code/app/src/test/java/com/example/experiment_automata/SubscriptionTest.java

Subscription class had a couple of errors along with other stuff so I fixed it.
Also added test for some of the classes I made

Bug fixes and testing

---

code/app/src/main/java/com/example/experiment_automata/User.java

Creates a static function for the User class. Given a UUID, it queries the firestore and returns the specified user.

create user from UUID

---

code/app/src/test/java/com/example/experiment_automata/ExperimentManagerTest.java

Implemented unit tests for the ExperimentManager class.
Closes #77

Experiment manager tests

---

code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/ExperimentManager.java
code/app/src/main/java/com/example/experiment_automata/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/AddCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/AddTrial/AddBinomialTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/AddTrial/AddCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/AddTrial/AddMeasurementTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/AddTrial/AddNaturalCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/Screen.java
code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
code/app/src/main/res/layout/fragment_add_binomial_trial.xml
code/app/src/main/res/layout/fragment_add_count_trial.xml
code/app/src/main/res/layout/fragment_add_measurement_trial.xml
code/app/src/main/res/layout/fragment_add_natural_count_trial.xml
code/app/src/main/res/navigation/mobile_navigation.xml
code/app/src/main/res/values/strings.xml

Visual implementation of #32. Shows a snackbar on empty input. Loose implementation of the UI mockup. Will have to discuss reimplementing this during a meeting. For now, this provides an MVP.

Add trial navigation

---

code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
code/app/src/main/res/layout/fragment_statistics.xml
code/app/src/main/res/values/strings.xml
code/app/src/test/java/com/example/experiment_automata/BinomialExperimentStatTest.java
code/app/src/test/java/com/example/experiment_automata/MeasurementStatTest.java
code/app/src/test/java/com/example/experiment_automata/NaturalCountStatTest.java

Added UI so that the stats functions are available in the UI for each experiment 
Increased testing for quartile functions to 3 and 4 data points
Extended quartile function to 3 data points
Replaced a hand-coded string with a new string from strings.xml

Display stats

---

code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
code/app/src/main/java/com/example/experiment_automata/Graphable.java
code/app/src/main/res/layout/fragment_histogram.xml
code/app/src/main/res/layout/fragment_nav_experiment_details.xml
code/app/src/main/res/layout/fragment_results.xml
code/app/src/main/res/values/dimens.xml

Made for #27 and #28. Uses MPAndroidChart.

Display graphs

---

code/app/src/androidTest/java/com/example/experiment_automata/BinomialTrialTests.java
code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
code/app/src/androidTest/java/com/example/experiment_automata/SearchUserStoriesTests.java
code/app/src/main/java/com/example/experiment_automata/LinkView.java
code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
code/app/src/main/java/com/example/experiment_automata/ui/LinkView.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/question/QuestionDisplay.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
code/app/src/main/res/layout/app_bar_main.xml
code/app/src/main/res/layout/fragment_profile.xml
code/app/src/main/res/layout/link_view.xml
code/app/src/main/res/layout/trial_layout.xml
code/app/src/main/res/values/attrs_link_view.xml

Link trial experimenter profile

---

code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java
code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
code/app/src/main/java/com/example/experiment_automata/ui/LinkView.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/question/ReplyArrayAdapter.java
code/app/src/main/java/com/example/experiment_automata/ui/question/SingleQuestionDisplay.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
code/app/src/main/res/layout/main_question_display.xml
code/app/src/main/res/layout/reply_layout_list.xml

Made for #115. Questions and replies are now preceded by usernames that link to their profiles.

Link Q&A user profile

---

code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapUtility.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java

Why it happens:
Non-location do not appear to activate FAB changing set up fix.  Fix for point in the future

Making non-location edit 

---

code/app/src/main/java/com/example/experiment_automata/backend/trials/BinomialTrial.java
code/app/src/main/java/com/example/experiment_automata/backend/trials/CountTrial.java
code/app/src/main/java/com/example/experiment_automata/backend/trials/MeasurementTrial.java
code/app/src/main/java/com/example/experiment_automata/backend/trials/NaturalCountTrial.java
code/app/src/main/java/com/example/experiment_automata/backend/trials/Trial.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/test/java/com/example/experiment_automata/TrialTest.java

Refactoring after some discussion in #132.

Trial refactoring

---

code/app/src/main/res/navigation/mobile_navigation.xml

(Avoided the issue of instant load)

changed home screen to profile

---

code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapDisplayFragment.java
code/app/src/main/res/layout/fragment_map_display_fragment.xml
code/app/src/main/res/values/strings.xml

Map appeared despite that experiment not needing it

map fixed for subscription

---

code/app/build.gradle
code/app/src/androidTest/java/com/example/experiment_automata/ExperimentTestWithFirebase.java
code/app/src/androidTest/java/com/example/experiment_automata/MeasurementStatTest.java
code/app/src/androidTest/java/com/example/experiment_automata/NaturalCountStatTest.java

All other test cases have now been fixed. 
Whoever reviews let me know if the main system breaks when you run it.

Al other test cases fix

---

code/app/src/androidTest/java/com/example/experiment_automata/BinomialStatsTestsWithFirebase.java

fixed binomial stats tests

---

code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Question.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/question/QuestionDisplay.java

Questions and Replies are now Put into Firebase and retrieved from Firebase. Experiment is also updated to push changes to Experiments to firebase when they happen

Questions and Replies put into Firebase

---

code/app/src/main/java/com/example/experiment_automata/backend/experiments/BinomialExperiment.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/CountExperiment.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/MeasurementExperiment.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/NaturalCountExperiment.java
code/app/src/main/java/com/example/experiment_automata/backend/trials/Trial.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
code/app/src/main/res/layout/experiment_layout.xml

Added Trial Firebase Integration.

Trial firebase

---

code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
code/app/src/main/res/layout/fragment_nav_experiment_details.xml

Show the minimum trials needed for an experiment in details screen

---

code/app/src/main/res/layout/fragment_profile.xml

Make the phone number and email address clickable if it's valid.

Clickable contact info

---

code/app/src/main/java/com/example/experiment_automata/backend/questions/Question.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java
code/app/src/test/java/com/example/experiment_automata/QuestionManagerTest.java
code/app/src/test/java/com/example/experiment_automata/QuestionTest.java
code/app/src/test/java/com/example/experiment_automata/ReplyTest.java

- Implemented TEST_MODE for questionManager so that it know when to use Firestore functionality.
- Fixed compareTo method in Reply since it was inconsistent with other pieces and filtered lowercase letters for one object.
- Added some more Javadoc to all methods in Question, Reply, and QuestionManager
- Implemented Unit Testing for Question, Reply, and QuestionManager. Every function is tested (except for constructors that require Firebase or Firebase functionality).

Question unit testing & tweaks

---

code/app/src/main/java/com/example/experiment_automata/backend/questions/Question.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java

Change the remaining calls to getInstanceTesting to getInstance in non-testing code

change database.getInstanceTesting to getInstance

---

code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
code/app/src/main/res/layout/fragment_nav_experiment_details.xml
code/app/src/test/java/com/example/experiment_automata/CountStatsTest.java
code/app/src/test/java/com/example/experiment_automata/ExperimentTest.java

Fixes to the display and editing of Experiment region variable

Region fixes

---

code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeManager.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java

revolt against logs, return to no log

Remove Log statements

---

code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeManager.java
code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeReference.java
code/app/src/main/java/com/example/experiment_automata/backend/barcode/BinomialBarcodeReference.java
code/app/src/main/java/com/example/experiment_automata/backend/barcode/CountBarcodeReference.java
code/app/src/main/java/com/example/experiment_automata/backend/barcode/MeasurementBarcodeReference.java
code/app/src/main/java/com/example/experiment_automata/backend/barcode/NaturalBarcodeReference.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/CountExperiment.java
code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/Question.java
code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/qr/ScanQRFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapUtility.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java

Remove the import statements for logs in some places that were missed

remove log

---

code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
code/app/src/main/res/layout/trial_layout.xml
code/app/src/main/res/values/dimens.xml

Only owners of an experiment can change the trials to be ignored or not. Experimenters no longer have the ability.

Ignore trials only owner
